# Generated by Django 5.1.1 on 2024-09-09 01:24

import musicapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicroom',
            name='title',
            field=models.CharField(default=musicapi.models.generate_unique_title, max_length=8, unique=True),
        ),
    ]
