# Generated by Django 5.1.1 on 2024-09-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_userprofile_person_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='apprentice',
            new_name='customer',
        ),
    ]
