# Generated by Django 4.1.4 on 2023-03-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Info',
        ),
    ]
